version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENERS_SECURITY_PROTOCOL: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT:PLAINTEXT
      KAFKA_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "match_events:1:1,match_results:1:1,bettings_events:1:1"

    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092"]
      interval: 10s
      timeout: 30s
      retries: 5
    ports:
      - "9092:9092"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  betting_api:
    build: .
    command: sh -c "./wait-for-kafka.sh kafka 9092 && node betting_api.js"
    depends_on:
      kafka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      KAFKA_BROKER: kafka:9092
      RABBITMQ_URL: amqp://guest:guest@rabbitmq
    ports:
      - "8080:8080"

  match_generator:
    build: .
    command: sh -c "./wait-for-kafka.sh kafka 9092 && node match_generator.js"
    depends_on:
      kafka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      KAFKA_BROKER: kafka:9092
      RABBITMQ_URL: amqp://guest:guest@rabbitmq

  match_simulator:
    build: .
    command: sh -c "./wait-for-kafka.sh kafka 9092 && node match_simulator.js"
    depends_on:
      kafka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      KAFKA_BROKER: kafka:9092
      RABBITMQ_URL: amqp://guest:guest@rabbitmq

  results_engine:
    build: .
    command: sh -c "./wait-for-kafka.sh kafka 9092 && node results_engine.js"
    depends_on:
      kafka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      KAFKA_BROKER: kafka:9092
      RABBITMQ_URL: amqp://guest:guest@rabbitmq

  dashboard_backend:
    build: .
    command: sh -c "./wait-for-kafka.sh kafka 9092 && node dashboard_backend.js"
    ports:
      - "8081:8081"
    depends_on:
      kafka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq

  email_worker:
    build: .
    command: sh -c "./wait-for-kafka.sh kafka 9092 && node email_worker.js"
    depends_on:
      kafka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq
    restart: always
